#!/bin/bash
# Reverses the actions of bootstrap
#

echo "- removing m4 macros"
rm -f aclocal.m4
rm -rf autom4te.cache

echo "- removing configuration header"
rm -f config.h.in

echo "- removing makefile inputs"
rm -f `find . -name Makefile.in`

echo "- removing conifgure script"
rm -f configure

echo "UNBOOTSTRAP COMPLETE"

